/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alpha: typeof import('./components/ColorPicker/Alpha.vue')['default']
    Checkboard: typeof import('./components/ColorPicker/Checkboard.vue')['default']
    CheckboxButton: typeof import('./components/CheckboxButton.vue')['default']
    CheckboxButtonGroup: typeof import('./components/CheckboxButtonGroup.vue')['default']
    ColorPicker: typeof import('./components/ColorPicker/index.vue')['default']
    Contextmenu: typeof import('./components/Contextmenu/index.vue')['default']
    EditableInput: typeof import('./components/ColorPicker/EditableInput.vue')['default']
    FileInput: typeof import('./components/FileInput.vue')['default']
    FormulaContent: typeof import('./components/LaTeXEditor/FormulaContent.vue')['default']
    FullscreenSpin: typeof import('./components/FullscreenSpin.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Hue: typeof import('./components/ColorPicker/Hue.vue')['default']
    LaTeXEditor: typeof import('./components/LaTeXEditor/index.vue')['default']
    MenuContent: typeof import('./components/Contextmenu/MenuContent.vue')['default']
    MoveablePanel: typeof import('./components/MoveablePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Saturation: typeof import('./components/ColorPicker/Saturation.vue')['default']
    SymbolContent: typeof import('./components/LaTeXEditor/SymbolContent.vue')['default']
    WritingBoard: typeof import('./components/WritingBoard.vue')['default']
  }
}
